package clientews.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source
 * version: 2.2
 *
 */
@WebService(name = "ServicioConvertidorInterfaz", targetNamespace = "http://beans/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioConvertidorInterfaz {

    /**
     *
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertir", targetNamespace = "http://beans/", className = "clientews.servicio.Convertir")
    @ResponseWrapper(localName = "convertirResponse", targetNamespace = "http://beans/", className = "clientews.servicio.ConvertirResponse")
    @Action(input = "http://beans/ServicioConvertidorInterfaz/convertirRequest", output = "http://beans/ServicioConvertidorInterfaz/convertirResponse")
    public String convertir(
            @WebParam(name = "arg0", targetNamespace = "") String arg0);

}
